#!/bin/bash
#----------------------------------------------------
# SLURM job script to run MPI applications on
# TACC's Stampede system.
#
#----------------------------------------------------
#SBATCH -J jacobi2D-mpi       # Job name
#SBATCH -o jacobi2D-mpi.o%j   # Name of stdout output file (%j expands to jobId)
#SBATCH -p development        # Queue name
#SBATCH -N 2                  # Total number of nodes requested (16 cores/node)
#SBATCH -n 16                 # Total number of mpi tasks requested
#SBATCH -t 00:30:00           # Run time (hh:mm:ss) - 0.5 hours

#SBATCH -A TG-ASC170005        # Allocation name to charge job against

# Launch the MPI executable named "a.out"

ibrun ./jacobi2D-mpi 100 100
